FROM golang:1.17-alpine AS base

WORKDIR /app

COPY ./go.*  ./
RUN go mod download

COPY ./ ./

FROM base AS go-builder

ENV CGO_ENABLED=0 \
  GOOS=linux \
  GOARCH=amd64
RUN --mount=target=. \
  --mount=type=cache,target=/root/.cache/go-build \
  go build -a -tags netgo -ldflags "-w -s" -o "/bin/" ./cmd/...

FROM scratch AS production
COPY --from=go-builder /bin/ /bin/

ENTRYPOINT [ "/bin/app" ]
