version: '3'

services:
  wwdatabase:
    container_name: wwdatabase-db
    image: postgres:latest
    env_file:
      - ./.env
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
volumes:
  database-data:
